export default {
  ADD_POST_REQUEST: 'posts/ADD_POST_REQUEST',
  ADD_POST_SUCCESS: 'posts/ADD_POST_SUCCESS',
  ADD_POST_ERROR: 'posts/ADD_POST_ERROR',
  RETRIEVE_POSTS_REQUEST: 'posts/RETRIEVE_POSTS_REQUEST',
  RETRIEVE_POSTS_SUCCESS: 'posts/RETRIEVE_POSTS_SUCCESS',
  RETRIEVE_POSTS_ERROR: 'posts/RETRIEVE_POSTS_ERROR',
};
