export default {
  RETRIEVE_SINGLE_POST_REQUEST: 'posts/RETRIEVE_SINGLE_POST_REQUEST',
  RETRIEVE_SINGLE_POST_SUCCESS: 'posts/RETRIEVE_SINGLE_POST_SUCCESS',
  RETRIEVE_SINGLE_POST_ERROR: 'posts/RETRIEVE_SINGLE_POST_ERROR',
  RETRIEVE_POSTS_REQUEST: 'posts/RETRIEVE_POSTS_REQUEST',
  RETRIEVE_POSTS_SUCCESS: 'posts/RETRIEVE_POSTS_SUCCESS',
  RETRIEVE_POSTS_ERROR: 'posts/RETRIEVE_POSTS_ERROR',
  VOTE_IN_POST_REQUEST: 'posts/VOTE_IN_POST_REQUEST',
  VOTE_IN_POST_SUCCESS: 'posts/VOTE_IN_POST_SUCCESS',
  VOTE_IN_POST_ERROR: 'posts/VOTE_IN_POST_ERROR',
};
