export default {
  RETRIEVE_SINGLE_COMMENT_REQUEST: 'comments/RETRIEVE_SINGLE_COMMENT_REQUEST',
  RETRIEVE_SINGLE_COMMENT_SUCCESS: 'comments/RETRIEVE_SINGLE_COMMENT_SUCCESS',
  RETRIEVE_SINGLE_COMMENT_ERROR: 'comments/RETRIEVE_SINGLE_COMMENT_ERROR',
  RETRIEVE_COMMENTS_REQUEST: 'comments/RETRIEVE_COMMENTS_REQUEST',
  RETRIEVE_COMMENTS_SUCCESS: 'comments/RETRIEVE_COMMENTS_SUCCESS',
  RETRIEVE_COMMENTS_ERROR: 'comments/RETRIEVE_COMMENTS_ERROR',
  VOTE_IN_COMMENT_REQUEST: 'comments/VOTE_IN_COMMENT_REQUEST',
  VOTE_IN_COMMENT_SUCCESS: 'comments/VOTE_IN_COMMENT_SUCCESS',
  VOTE_IN_COMMENT_ERROR: 'comments/VOTE_IN_COMMENT_ERROR',
  ADD_COMMENT_REQUEST: 'comments/ADD_COMMENT_REQUEST',
  ADD_COMMENT_SUCCESS: 'comments/ADD_COMMENT_SUCCESS',
  ADD_COMMENT_ERROR: 'comments/ADD_COMMENT_ERROR',
};
